on:
  push:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        run: |
          echo "hello"
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -l -a
      - run: ls -l -a ${{ github.workspace	}}