on:
  push:
  workflow_dispatch:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: theowenyoung/act
          ref: feature/run-id
      - uses: actions/setup-go@v2
      - run: make build
      - uses: actions/upload-artifact@v2
        with:
          name: actbin
          path: dist/local/act