name: BuildData2

on:
  workflow_dispatch:
    input:
      part:
        description: 'part'
        required: true
        default: ''
  schedule:
    - cron: '42 14 * * *'

jobs:
  translation:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Get time to
        id: time
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log('github',process.env.TEST_TOKEN)
            const now = Date.now();
            console.log('now',now)
            const specificDate = new Date();
            specificDate.setUTCHours(14);
            specificDate.setUTCMinutes(50);
            console.log('specificDate',specificDate)
            const diff = specificDate.getTime()-now;
            const sleep = (time)=>{
              return new Promise((resolve)=>{
                console.log(`sleep for ${diff}ms`)
                setTimeout(()=>{
                  resolve()
                },time)
              })
            }
            if(diff>0){
              await sleep(diff)
            }
            return {"message":"Hello"}
      - name: echo
        run: echo ${{ github.event.inputs.part || secrets.PART }}