on:
  workflow_dispatch:
jobs:
  script:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Format message
        id: format
        uses: actions/github-script@v2
        env:
          TEST_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log('github',process.env.TEST_TOKEN)
            return {"message":"Hello 2%"}