on:
  workflow_dispatch:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -l -a
      - run: sleep 5m
      - run: echo 2222