on:
  push:
  workflow_dispatch:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls -l -a
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test