on:
  push:
  workflow_dispatch:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup act
        uses: actionsflow/setup-act-for-actionsflow@v1
      - name: Print Outputs
        run: |
          echo "hello"
      - name: run act
        run: act -W ./workflows
          