on:
  push:
  workflow_dispatch:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v3
        id: get-cache-key-result
        with:
          script: |
            const artifacts = await github.actions.listArtifactsForRepo({
              owner:context.repo.owner,
              repo:context.repo.repo,
            });
            console.log(artifacts.data.artifacts)

          result-encoding: string
      - run: echo "::set-output name=hash::${{hashFiles('README.md')}}"
        id: cache-key
      - run: echo ${{steps.cache-key.outputs.hash}} >> cache-key.txt
      - uses: actions/upload-artifact@v2
        with:
          name: actionsflow-cache-key____${{steps.cache-key.outputs.hash}}
          path: cache-key.txt
          if-no-files-found: ignore
      - name: Push Cache Branch
        if: false
        run: |-
          mkdir -p .actionsflow-cache-temp
          cd .actionsflow-cache-temp
          echo $(date '+%F_%H:%M:%S' ) >>text.txt
          ls -l
          git init
          git checkout --orphan test
          git config user.name Nicolas
          git config user.email ttttt@gmail.com
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}.git
          git add --all
          git commit -m "chore: backup cache key file"
          git push origin --force test