on:
  workflow_dispatch:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -l -a
      - run: ls -l -a ${{ github.workspace	}}
      - name: Get IsPreReLease
        id: is-prerelease
        run: echo ::set-output name=result::[ $(cat .releaseflag | cut -c1-3) = pre ] && echo true || echo false
      - name: get is pre
        run: echo ${{ steps.is-prerelease.outputs.result }}