on:
  push:
  workflow_dispatch:
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $(date '+%F_%H:%M:%S' ) >>text.txt
      - uses: pat-s/always-upload-cache@master
        with:
          path: |
            text.txt
          key: testcachekey
      - run: ls -l && cat text.txt
        name: echo cache
      - name: Push Cache Branch
        if: false
        run: |-
          mkdir -p .actionsflow-cache-temp
          cd .actionsflow-cache-temp
          echo $(date '+%F_%H:%M:%S' ) >>text.txt
          ls -l
          git init
          git checkout --orphan test
          git config user.name Nicolas
          git config user.email ttttt@gmail.com
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{github.repository}}.git
          git add --all
          git commit -m "chore: backup cache key file"
          git push origin --force test